//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Arts struct {
	ID          *int32 `sql:"primary_key"`
	CoverURL    string
	Name        string
	Description string
	CreatorID   int32
	Price       int32
	CreatedAt   *time.Time
	UpdatedAt   *time.Time
}
