//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Codes struct {
	ID      *int32 `sql:"primary_key"`
	Name    string
	Value   int32
	ExpTime time.Time
}
