//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Files struct {
	ID        *int32 `sql:"primary_key"`
	ArtID     int32
	Filename  string
	Filetype  string
	URL       string
	CreatedAt *time.Time
	UpdatedAt *time.Time
}
