//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Follow struct {
	UserIDFollower int32 `sql:"primary_key"`
	UserIDFollowee int32 `sql:"primary_key"`
	CreatedAt      *time.Time
}
