//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type UsersBoughtArts struct {
	UserID int32 `sql:"primary_key"`
	ArtID  int32 `sql:"primary_key"`
}
