-- BEGIN;
--
-- INSERT INTO "users" (
--   "username",
--   "email",
--   "password",
-- )
-- VALUES
--   ('deepaung', 'i.deepaung@gmail.com', 'password'),
--   ('test', 'test@gmail.com', 'password'),
--   ('example', 'example@gmail.com', 'password'),
--
-- COMMIT;
