//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Arts = newArtsTable("", "arts", "")

type artsTable struct {
	sqlite.Table

	// Columns
	ID          sqlite.ColumnInteger
	CoverURL    sqlite.ColumnString
	Name        sqlite.ColumnString
	Description sqlite.ColumnString
	CreatorID   sqlite.ColumnInteger
	Price       sqlite.ColumnInteger
	CreatedAt   sqlite.ColumnTimestamp
	UpdatedAt   sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type ArtsTable struct {
	artsTable

	EXCLUDED artsTable
}

// AS creates new ArtsTable with assigned alias
func (a ArtsTable) AS(alias string) *ArtsTable {
	return newArtsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ArtsTable with assigned schema name
func (a ArtsTable) FromSchema(schemaName string) *ArtsTable {
	return newArtsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ArtsTable with assigned table prefix
func (a ArtsTable) WithPrefix(prefix string) *ArtsTable {
	return newArtsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ArtsTable with assigned table suffix
func (a ArtsTable) WithSuffix(suffix string) *ArtsTable {
	return newArtsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newArtsTable(schemaName, tableName, alias string) *ArtsTable {
	return &ArtsTable{
		artsTable: newArtsTableImpl(schemaName, tableName, alias),
		EXCLUDED:  newArtsTableImpl("", "excluded", ""),
	}
}

func newArtsTableImpl(schemaName, tableName, alias string) artsTable {
	var (
		IDColumn          = sqlite.IntegerColumn("id")
		CoverURLColumn    = sqlite.StringColumn("cover_url")
		NameColumn        = sqlite.StringColumn("name")
		DescriptionColumn = sqlite.StringColumn("description")
		CreatorIDColumn   = sqlite.IntegerColumn("creator_id")
		PriceColumn       = sqlite.IntegerColumn("price")
		CreatedAtColumn   = sqlite.TimestampColumn("created_at")
		UpdatedAtColumn   = sqlite.TimestampColumn("updated_at")
		allColumns        = sqlite.ColumnList{IDColumn, CoverURLColumn, NameColumn, DescriptionColumn, CreatorIDColumn, PriceColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = sqlite.ColumnList{CoverURLColumn, NameColumn, DescriptionColumn, CreatorIDColumn, PriceColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return artsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		CoverURL:    CoverURLColumn,
		Name:        NameColumn,
		Description: DescriptionColumn,
		CreatorID:   CreatorIDColumn,
		Price:       PriceColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
