//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var ArtsTags = newArtsTagsTable("", "arts_tags", "")

type artsTagsTable struct {
	sqlite.Table

	// Columns
	ArtID sqlite.ColumnInteger
	TagID sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type ArtsTagsTable struct {
	artsTagsTable

	EXCLUDED artsTagsTable
}

// AS creates new ArtsTagsTable with assigned alias
func (a ArtsTagsTable) AS(alias string) *ArtsTagsTable {
	return newArtsTagsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ArtsTagsTable with assigned schema name
func (a ArtsTagsTable) FromSchema(schemaName string) *ArtsTagsTable {
	return newArtsTagsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ArtsTagsTable with assigned table prefix
func (a ArtsTagsTable) WithPrefix(prefix string) *ArtsTagsTable {
	return newArtsTagsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ArtsTagsTable with assigned table suffix
func (a ArtsTagsTable) WithSuffix(suffix string) *ArtsTagsTable {
	return newArtsTagsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newArtsTagsTable(schemaName, tableName, alias string) *ArtsTagsTable {
	return &ArtsTagsTable{
		artsTagsTable: newArtsTagsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newArtsTagsTableImpl("", "excluded", ""),
	}
}

func newArtsTagsTableImpl(schemaName, tableName, alias string) artsTagsTable {
	var (
		ArtIDColumn    = sqlite.IntegerColumn("art_id")
		TagIDColumn    = sqlite.IntegerColumn("tag_id")
		allColumns     = sqlite.ColumnList{ArtIDColumn, TagIDColumn}
		mutableColumns = sqlite.ColumnList{}
	)

	return artsTagsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ArtID: ArtIDColumn,
		TagID: TagIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
