//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Codes = newCodesTable("", "codes", "")

type codesTable struct {
	sqlite.Table

	// Columns
	ID      sqlite.ColumnInteger
	Name    sqlite.ColumnString
	Value   sqlite.ColumnInteger
	ExpTime sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type CodesTable struct {
	codesTable

	EXCLUDED codesTable
}

// AS creates new CodesTable with assigned alias
func (a CodesTable) AS(alias string) *CodesTable {
	return newCodesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CodesTable with assigned schema name
func (a CodesTable) FromSchema(schemaName string) *CodesTable {
	return newCodesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CodesTable with assigned table prefix
func (a CodesTable) WithPrefix(prefix string) *CodesTable {
	return newCodesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CodesTable with assigned table suffix
func (a CodesTable) WithSuffix(suffix string) *CodesTable {
	return newCodesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCodesTable(schemaName, tableName, alias string) *CodesTable {
	return &CodesTable{
		codesTable: newCodesTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newCodesTableImpl("", "excluded", ""),
	}
}

func newCodesTableImpl(schemaName, tableName, alias string) codesTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		NameColumn     = sqlite.StringColumn("name")
		ValueColumn    = sqlite.IntegerColumn("value")
		ExpTimeColumn  = sqlite.TimestampColumn("exp_time")
		allColumns     = sqlite.ColumnList{IDColumn, NameColumn, ValueColumn, ExpTimeColumn}
		mutableColumns = sqlite.ColumnList{NameColumn, ValueColumn, ExpTimeColumn}
	)

	return codesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:      IDColumn,
		Name:    NameColumn,
		Value:   ValueColumn,
		ExpTime: ExpTimeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
