//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var DownloadedArts = newDownloadedArtsTable("", "downloaded_arts", "")

type downloadedArtsTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	ArtID     sqlite.ColumnInteger
	CreatedAt sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type DownloadedArtsTable struct {
	downloadedArtsTable

	EXCLUDED downloadedArtsTable
}

// AS creates new DownloadedArtsTable with assigned alias
func (a DownloadedArtsTable) AS(alias string) *DownloadedArtsTable {
	return newDownloadedArtsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new DownloadedArtsTable with assigned schema name
func (a DownloadedArtsTable) FromSchema(schemaName string) *DownloadedArtsTable {
	return newDownloadedArtsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new DownloadedArtsTable with assigned table prefix
func (a DownloadedArtsTable) WithPrefix(prefix string) *DownloadedArtsTable {
	return newDownloadedArtsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new DownloadedArtsTable with assigned table suffix
func (a DownloadedArtsTable) WithSuffix(suffix string) *DownloadedArtsTable {
	return newDownloadedArtsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newDownloadedArtsTable(schemaName, tableName, alias string) *DownloadedArtsTable {
	return &DownloadedArtsTable{
		downloadedArtsTable: newDownloadedArtsTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newDownloadedArtsTableImpl("", "excluded", ""),
	}
}

func newDownloadedArtsTableImpl(schemaName, tableName, alias string) downloadedArtsTable {
	var (
		IDColumn        = sqlite.IntegerColumn("id")
		ArtIDColumn     = sqlite.IntegerColumn("art_id")
		CreatedAtColumn = sqlite.TimestampColumn("created_at")
		allColumns      = sqlite.ColumnList{IDColumn, ArtIDColumn, CreatedAtColumn}
		mutableColumns  = sqlite.ColumnList{ArtIDColumn, CreatedAtColumn}
	)

	return downloadedArtsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		ArtID:     ArtIDColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
