//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Files = newFilesTable("", "files", "")

type filesTable struct {
	sqlite.Table

	// Columns
	ID        sqlite.ColumnInteger
	ArtID     sqlite.ColumnInteger
	Filename  sqlite.ColumnString
	Filetype  sqlite.ColumnString
	URL       sqlite.ColumnString
	CreatedAt sqlite.ColumnTimestamp
	UpdatedAt sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type FilesTable struct {
	filesTable

	EXCLUDED filesTable
}

// AS creates new FilesTable with assigned alias
func (a FilesTable) AS(alias string) *FilesTable {
	return newFilesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FilesTable with assigned schema name
func (a FilesTable) FromSchema(schemaName string) *FilesTable {
	return newFilesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FilesTable with assigned table prefix
func (a FilesTable) WithPrefix(prefix string) *FilesTable {
	return newFilesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FilesTable with assigned table suffix
func (a FilesTable) WithSuffix(suffix string) *FilesTable {
	return newFilesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFilesTable(schemaName, tableName, alias string) *FilesTable {
	return &FilesTable{
		filesTable: newFilesTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newFilesTableImpl("", "excluded", ""),
	}
}

func newFilesTableImpl(schemaName, tableName, alias string) filesTable {
	var (
		IDColumn        = sqlite.IntegerColumn("id")
		ArtIDColumn     = sqlite.IntegerColumn("art_id")
		FilenameColumn  = sqlite.StringColumn("filename")
		FiletypeColumn  = sqlite.StringColumn("filetype")
		URLColumn       = sqlite.StringColumn("url")
		CreatedAtColumn = sqlite.TimestampColumn("created_at")
		UpdatedAtColumn = sqlite.TimestampColumn("updated_at")
		allColumns      = sqlite.ColumnList{IDColumn, ArtIDColumn, FilenameColumn, FiletypeColumn, URLColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns  = sqlite.ColumnList{ArtIDColumn, FilenameColumn, FiletypeColumn, URLColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return filesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		ArtID:     ArtIDColumn,
		Filename:  FilenameColumn,
		Filetype:  FiletypeColumn,
		URL:       URLColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
