//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Follow = newFollowTable("", "follow", "")

type followTable struct {
	sqlite.Table

	// Columns
	UserIDFollower sqlite.ColumnInteger
	UserIDFollowee sqlite.ColumnInteger
	CreatedAt      sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type FollowTable struct {
	followTable

	EXCLUDED followTable
}

// AS creates new FollowTable with assigned alias
func (a FollowTable) AS(alias string) *FollowTable {
	return newFollowTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new FollowTable with assigned schema name
func (a FollowTable) FromSchema(schemaName string) *FollowTable {
	return newFollowTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new FollowTable with assigned table prefix
func (a FollowTable) WithPrefix(prefix string) *FollowTable {
	return newFollowTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new FollowTable with assigned table suffix
func (a FollowTable) WithSuffix(suffix string) *FollowTable {
	return newFollowTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newFollowTable(schemaName, tableName, alias string) *FollowTable {
	return &FollowTable{
		followTable: newFollowTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newFollowTableImpl("", "excluded", ""),
	}
}

func newFollowTableImpl(schemaName, tableName, alias string) followTable {
	var (
		UserIDFollowerColumn = sqlite.IntegerColumn("user_id_follower")
		UserIDFolloweeColumn = sqlite.IntegerColumn("user_id_followee")
		CreatedAtColumn      = sqlite.TimestampColumn("created_at")
		allColumns           = sqlite.ColumnList{UserIDFollowerColumn, UserIDFolloweeColumn, CreatedAtColumn}
		mutableColumns       = sqlite.ColumnList{CreatedAtColumn}
	)

	return followTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserIDFollower: UserIDFollowerColumn,
		UserIDFollowee: UserIDFolloweeColumn,
		CreatedAt:      CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
