//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Oauths = newOauthsTable("", "oauths", "")

type oauthsTable struct {
	sqlite.Table

	// Columns
	UserID         sqlite.ColumnInteger
	Provider       sqlite.ColumnString
	ProviderUserID sqlite.ColumnString
	CreatedAt      sqlite.ColumnTimestamp
	UpdatedAt      sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type OauthsTable struct {
	oauthsTable

	EXCLUDED oauthsTable
}

// AS creates new OauthsTable with assigned alias
func (a OauthsTable) AS(alias string) *OauthsTable {
	return newOauthsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OauthsTable with assigned schema name
func (a OauthsTable) FromSchema(schemaName string) *OauthsTable {
	return newOauthsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OauthsTable with assigned table prefix
func (a OauthsTable) WithPrefix(prefix string) *OauthsTable {
	return newOauthsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OauthsTable with assigned table suffix
func (a OauthsTable) WithSuffix(suffix string) *OauthsTable {
	return newOauthsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOauthsTable(schemaName, tableName, alias string) *OauthsTable {
	return &OauthsTable{
		oauthsTable: newOauthsTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newOauthsTableImpl("", "excluded", ""),
	}
}

func newOauthsTableImpl(schemaName, tableName, alias string) oauthsTable {
	var (
		UserIDColumn         = sqlite.IntegerColumn("user_id")
		ProviderColumn       = sqlite.StringColumn("provider")
		ProviderUserIDColumn = sqlite.StringColumn("provider_user_id")
		CreatedAtColumn      = sqlite.TimestampColumn("created_at")
		UpdatedAtColumn      = sqlite.TimestampColumn("updated_at")
		allColumns           = sqlite.ColumnList{UserIDColumn, ProviderColumn, ProviderUserIDColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns       = sqlite.ColumnList{UserIDColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return oauthsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:         UserIDColumn,
		Provider:       ProviderColumn,
		ProviderUserID: ProviderUserIDColumn,
		CreatedAt:      CreatedAtColumn,
		UpdatedAt:      UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
