//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Arts = Arts.FromSchema(schema)
	ArtsTags = ArtsTags.FromSchema(schema)
	Codes = Codes.FromSchema(schema)
	DownloadedArts = DownloadedArts.FromSchema(schema)
	Files = Files.FromSchema(schema)
	Follow = Follow.FromSchema(schema)
	Oauths = Oauths.FromSchema(schema)
	SchemaMigrations = SchemaMigrations.FromSchema(schema)
	Tags = Tags.FromSchema(schema)
	Tokens = Tokens.FromSchema(schema)
	Users = Users.FromSchema(schema)
	UsersBoughtArts = UsersBoughtArts.FromSchema(schema)
	UsersStarredArts = UsersStarredArts.FromSchema(schema)
	UsersUsedCodes = UsersUsedCodes.FromSchema(schema)
}
