//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var UsersStarredArts = newUsersStarredArtsTable("", "users_starred_arts", "")

type usersStarredArtsTable struct {
	sqlite.Table

	// Columns
	UserID    sqlite.ColumnInteger
	ArtID     sqlite.ColumnInteger
	CreatedAt sqlite.ColumnTimestamp

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type UsersStarredArtsTable struct {
	usersStarredArtsTable

	EXCLUDED usersStarredArtsTable
}

// AS creates new UsersStarredArtsTable with assigned alias
func (a UsersStarredArtsTable) AS(alias string) *UsersStarredArtsTable {
	return newUsersStarredArtsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersStarredArtsTable with assigned schema name
func (a UsersStarredArtsTable) FromSchema(schemaName string) *UsersStarredArtsTable {
	return newUsersStarredArtsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersStarredArtsTable with assigned table prefix
func (a UsersStarredArtsTable) WithPrefix(prefix string) *UsersStarredArtsTable {
	return newUsersStarredArtsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersStarredArtsTable with assigned table suffix
func (a UsersStarredArtsTable) WithSuffix(suffix string) *UsersStarredArtsTable {
	return newUsersStarredArtsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersStarredArtsTable(schemaName, tableName, alias string) *UsersStarredArtsTable {
	return &UsersStarredArtsTable{
		usersStarredArtsTable: newUsersStarredArtsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newUsersStarredArtsTableImpl("", "excluded", ""),
	}
}

func newUsersStarredArtsTableImpl(schemaName, tableName, alias string) usersStarredArtsTable {
	var (
		UserIDColumn    = sqlite.IntegerColumn("user_id")
		ArtIDColumn     = sqlite.IntegerColumn("art_id")
		CreatedAtColumn = sqlite.TimestampColumn("created_at")
		allColumns      = sqlite.ColumnList{UserIDColumn, ArtIDColumn, CreatedAtColumn}
		mutableColumns  = sqlite.ColumnList{CreatedAtColumn}
	)

	return usersStarredArtsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		ArtID:     ArtIDColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
