//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var UsersBoughtArts = newUsersBoughtArtsTable("", "users_bought_arts", "")

type usersBoughtArtsTable struct {
	sqlite.Table

	// Columns
	UserID sqlite.ColumnInteger
	ArtID  sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type UsersBoughtArtsTable struct {
	usersBoughtArtsTable

	EXCLUDED usersBoughtArtsTable
}

// AS creates new UsersBoughtArtsTable with assigned alias
func (a UsersBoughtArtsTable) AS(alias string) *UsersBoughtArtsTable {
	return newUsersBoughtArtsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersBoughtArtsTable with assigned schema name
func (a UsersBoughtArtsTable) FromSchema(schemaName string) *UsersBoughtArtsTable {
	return newUsersBoughtArtsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersBoughtArtsTable with assigned table prefix
func (a UsersBoughtArtsTable) WithPrefix(prefix string) *UsersBoughtArtsTable {
	return newUsersBoughtArtsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersBoughtArtsTable with assigned table suffix
func (a UsersBoughtArtsTable) WithSuffix(suffix string) *UsersBoughtArtsTable {
	return newUsersBoughtArtsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersBoughtArtsTable(schemaName, tableName, alias string) *UsersBoughtArtsTable {
	return &UsersBoughtArtsTable{
		usersBoughtArtsTable: newUsersBoughtArtsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newUsersBoughtArtsTableImpl("", "excluded", ""),
	}
}

func newUsersBoughtArtsTableImpl(schemaName, tableName, alias string) usersBoughtArtsTable {
	var (
		UserIDColumn   = sqlite.IntegerColumn("user_id")
		ArtIDColumn    = sqlite.IntegerColumn("art_id")
		allColumns     = sqlite.ColumnList{UserIDColumn, ArtIDColumn}
		mutableColumns = sqlite.ColumnList{}
	)

	return usersBoughtArtsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID: UserIDColumn,
		ArtID:  ArtIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
