//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var UsersUsedCodes = newUsersUsedCodesTable("", "users_used_codes", "")

type usersUsedCodesTable struct {
	sqlite.Table

	// Columns
	UserID sqlite.ColumnInteger
	CodeID sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type UsersUsedCodesTable struct {
	usersUsedCodesTable

	EXCLUDED usersUsedCodesTable
}

// AS creates new UsersUsedCodesTable with assigned alias
func (a UsersUsedCodesTable) AS(alias string) *UsersUsedCodesTable {
	return newUsersUsedCodesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UsersUsedCodesTable with assigned schema name
func (a UsersUsedCodesTable) FromSchema(schemaName string) *UsersUsedCodesTable {
	return newUsersUsedCodesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UsersUsedCodesTable with assigned table prefix
func (a UsersUsedCodesTable) WithPrefix(prefix string) *UsersUsedCodesTable {
	return newUsersUsedCodesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UsersUsedCodesTable with assigned table suffix
func (a UsersUsedCodesTable) WithSuffix(suffix string) *UsersUsedCodesTable {
	return newUsersUsedCodesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUsersUsedCodesTable(schemaName, tableName, alias string) *UsersUsedCodesTable {
	return &UsersUsedCodesTable{
		usersUsedCodesTable: newUsersUsedCodesTableImpl(schemaName, tableName, alias),
		EXCLUDED:            newUsersUsedCodesTableImpl("", "excluded", ""),
	}
}

func newUsersUsedCodesTableImpl(schemaName, tableName, alias string) usersUsedCodesTable {
	var (
		UserIDColumn   = sqlite.IntegerColumn("user_id")
		CodeIDColumn   = sqlite.IntegerColumn("code_id")
		allColumns     = sqlite.ColumnList{UserIDColumn, CodeIDColumn}
		mutableColumns = sqlite.ColumnList{}
	)

	return usersUsedCodesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID: UserIDColumn,
		CodeID: CodeIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
